# helm/ivodocker-chart/templates/job-migrations.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ivodocker-chart.fullname" . }}-migrations
  labels:
    {{- include "ivodocker-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          
          command:
            - npx
            - sequelize-cli
            - db:migrate
            - --config
            - config/config.js

          
          envFrom:
            - secretRef:
                name: {{ include "ivodocker-chart.fullname" . }}-db-credentials