# helm/ivodocker-chart/templates/job-migrations.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ivodocker-chart.fullname" . }}-migrations
  labels:
    {{- include "ivodocker-chart.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # ESTA É A PARTE MAIS IMPORTANTE:
          # Em vez de rodar o comando padrão da imagem, nós o substituímos
          # para executar apenas a migração do banco de dados.
          command: ["npx", "sequelize-cli", "db:migrate"]

          # O Job também precisa das credenciais do banco para se conectar!
          envFrom:
            - secretRef:
                name: {{ include "ivodocker-chart.fullname" . }}-db-credentials