apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ivodocker-chart.fullname" . }}-db-credentials
type: Opaque
data:
  DB_USER: {{ .Values.dbCredentials.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.dbCredentials.DB_PASSWORD | b64enc | quote }}
  DB_NAME: {{ .Values.dbCredentials.DB_NAME | b64enc | quote }}
  DB_HOST: {{ .Values.dbCredentials.DB_HOST | b64enc | quote }}