apiVersion: v1
kind: Service
metadata:
  name: mysql-prod
  namespace: prod
spec:
  selector:
    app.kubernetes.io/instance: mysql-innodbcluster-mysql-prod-mysql-server
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
