replicaCount: 1

image:
  repository: ghcr.io/paulohenriquejunio/ivodocker
  pullPolicy: IfNotPresent
  tag: b5e6db7

service:
  type: ClusterIP
  port: 3000

database:
  host: "mysql-dev"          # serviço do banco criado pelo operador
  name: "ivodocker_dev"
  user: "root"
  password: "password"