replicaCount: 2

# Image para produção. CI irá escrever a tag exata quando publicar a imagem.
image:
  repository: ghcr.io/paulohenriquejunio/ivodocker
  pullPolicy: IfNotPresent
  tag: fcda5e3

service:
  type: ClusterIP
  port: 3000

# Caso a imagem no GHCR seja privada, liste aqui os imagePullSecrets
imagePullSecrets:
  - name: ghcr-creds

database:
  host: "mysql-ivodocker"
  name: "ivodocker_db"
  user: "root"
  # Senha de produção (aqui apenas ilustrativa conforme solicitado)
  password: "prod_password"
