replicaCount: 1

image:
  repository: ghcr.io/paulohenriquejunio/ivodocker
  pullPolicy: IfNotPresent
  tag: 1a3fabc

service:
  type: ClusterIP
  port: 3000

createSecret: false

dbCredentials:
  DB_HOST: "mysql-dev"
  DB_USER: "root"
  DB_PASSWORD: "CHANGE_ME"
  DB_NAME: "ivodocker_dev"

rollout:
  enabled: true
  strategy: "blueGreen"
  blueGreen:
    autoPromotionEnabled: false
    scaleDownDelaySeconds: 30
