replicaCount: 1

image:
  repository: ghcr.io/paulohenriquejunio/ivodocker
  pullPolicy: IfNotPresent
  tag: 71283ea

service:
  type: ClusterIP
  port: 3000

database:
  host: "mysql-ivodocker"
  name: "ivodocker_db"
  user: "root"
  password: "password"
