replicaCount: 1

image:
  repository: ghcr.io/paulohenriquejunio/ivodocker
  pullPolicy: IfNotPresent
  tag: cc5fb06

service:
  type: ClusterIP
  port: 3000

database:
  host: "mysql-prod"         # serviço do banco em prod
  name: "ivodocker_prod"
  user: "root"
  password: "password"