apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivodocker-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PauloHenriqueJunio/ivodocker
    targetRevision: HEAD
    path: helm/ivodocker-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true