apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/PauloHenriqueJunio/ivodocker
    targetRevision: teste-argo-cd
    path: k8s/mysql-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
